/*
このセクションのポイント:

データメトリック関数（DMF）: Snowflake組み込みの品質チェック機構
システムDMF: NULL_COUNT, DUPLICATE_COUNT, UNIQUE_COUNT, ROW_COUNT, FRESHNESS
スケジュール実行: テーブル単位でDMFを紐付け、定期的に自動計測
結果の確認: SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS() で計測値を取得

※ Enterprise Edition 以上が必要です
*/
USE ROLE MU;
USE SCHEMA SECURITIES_WORKSHOP.RAW_DATA;

-- ============================================
-- 1. DMFの概要
-- ============================================
-- section1-copy_into.sql のセクション6〜8では、手動SQLで品質チェックを行いました。
-- DMFを使うと、同様のチェックをテーブルに紐付けて自動的・継続的に実行できます。
--
-- 手動SQL品質チェック:
--   - 毎回SQLを実行する必要がある
--   - 結果は自前のログテーブルに記録
--
-- DMF（データメトリック関数）:
--   - テーブルに紐付けてスケジュール実行
--   - 結果はSnowflakeが自動管理（トレンド分析可能）
--   - システムDMF（組み込み）とカスタムDMF（自作）がある

-- ============================================
-- 2. システムDMFの一覧確認
-- ============================================

-- Snowflakeが提供するシステムDMF一覧
-- SNOWFLAKE.CORE スキーマに格納されています
SHOW DATA METRIC FUNCTIONS IN SCHEMA SNOWFLAKE.CORE;

-- ============================================
-- 3. DMFをアドホック（単発）で実行してみる
-- ============================================

-- 顧客テーブルの CUSTOMER_ID のNULL件数
SELECT SNOWFLAKE.CORE.NULL_COUNT(
  SELECT CUSTOMER_ID FROM SECURITIES_WORKSHOP.RAW_DATA.CUSTOMERS
);

-- 顧客テーブルの CUSTOMER_ID のユニーク件数
SELECT SNOWFLAKE.CORE.UNIQUE_COUNT(
  SELECT CUSTOMER_ID FROM SECURITIES_WORKSHOP.RAW_DATA.CUSTOMERS
);

-- 顧客テーブルの CUSTOMER_ID の重複件数
SELECT SNOWFLAKE.CORE.DUPLICATE_COUNT(
  SELECT CUSTOMER_ID FROM SECURITIES_WORKSHOP.RAW_DATA.CUSTOMERS
);

-- 市場株価テーブルのフレッシュネス（最終更新からの経過時間）
SELECT SNOWFLAKE.CORE.FRESHNESS(
  SELECT LOAD_TIMESTAMP FROM SECURITIES_WORKSHOP.RAW_DATA.MARKET_PRICES
);

-- ============================================
-- 4. DMFをテーブルに紐付ける（継続監視の設定）
-- ============================================

-- まずスケジュールを設定（5分間隔）
-- ※ 実運用では '60 MINUTE' や 'USING CRON 0 8 * * * Asia/Tokyo' など適宜調整
ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.CUSTOMERS
  SET DATA_METRIC_SCHEDULE = '5 MINUTE';

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.HOLDINGS
  SET DATA_METRIC_SCHEDULE = '5 MINUTE';

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.MARKET_PRICES
  SET DATA_METRIC_SCHEDULE = '5 MINUTE';

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.DAILY_TRADES
  SET DATA_METRIC_SCHEDULE = '5 MINUTE';

-- ============================================
-- 4a. CUSTOMERS テーブルにDMFを紐付け
-- ============================================

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.CUSTOMERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.CUSTOMERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_NAME);

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.CUSTOMERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (CUSTOMER_ID);

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.CUSTOMERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.UNIQUE_COUNT ON (CUSTOMER_ID);

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.CUSTOMERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.CUSTOMERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (LOAD_TIMESTAMP);

-- ============================================
-- 4b. HOLDINGS テーブルにDMFを紐付け
-- ============================================

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.HOLDINGS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.HOLDINGS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (STOCK_CODE);

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.HOLDINGS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (CUSTOMER_ID);

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.HOLDINGS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

-- ============================================
-- 4c. MARKET_PRICES テーブルにDMFを紐付け
-- ============================================

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.MARKET_PRICES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (STOCK_CODE);

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.MARKET_PRICES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CLOSING_PRICE);

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.MARKET_PRICES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.MARKET_PRICES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (LOAD_TIMESTAMP);

-- ============================================
-- 4d. DAILY_TRADES テーブルにDMFを紐付け
-- ============================================

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.DAILY_TRADES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.DAILY_TRADES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (STOCK_CODE);

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.DAILY_TRADES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (TRADE_ID);

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.DAILY_TRADES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.DAILY_TRADES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (LOAD_TIMESTAMP);

-- ============================================
-- 5. 紐付け状況の確認
-- ============================================

SELECT
  REF_ENTITY_NAME  AS TABLE_NAME,
  METRIC_NAME,
  REF_ENTITY_DOMAIN,
  SCHEDULE,
  SCHEDULE_STATUS
FROM TABLE(
  SECURITIES_WORKSHOP.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
    REF_ENTITY_NAME => 'SECURITIES_WORKSHOP.RAW_DATA.CUSTOMERS',
    REF_ENTITY_DOMAIN => 'TABLE'
  )
);

SELECT
  REF_ENTITY_NAME  AS TABLE_NAME,
  METRIC_NAME,
  REF_ENTITY_DOMAIN,
  SCHEDULE,
  SCHEDULE_STATUS
FROM TABLE(
  SECURITIES_WORKSHOP.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
    REF_ENTITY_NAME => 'SECURITIES_WORKSHOP.RAW_DATA.HOLDINGS',
    REF_ENTITY_DOMAIN => 'TABLE'
  )
);

SELECT
  REF_ENTITY_NAME  AS TABLE_NAME,
  METRIC_NAME,
  REF_ENTITY_DOMAIN,
  SCHEDULE,
  SCHEDULE_STATUS
FROM TABLE(
  SECURITIES_WORKSHOP.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
    REF_ENTITY_NAME => 'SECURITIES_WORKSHOP.RAW_DATA.MARKET_PRICES',
    REF_ENTITY_DOMAIN => 'TABLE'
  )
);

SELECT
  REF_ENTITY_NAME  AS TABLE_NAME,
  METRIC_NAME,
  REF_ENTITY_DOMAIN,
  SCHEDULE,
  SCHEDULE_STATUS
FROM TABLE(
  SECURITIES_WORKSHOP.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
    REF_ENTITY_NAME => 'SECURITIES_WORKSHOP.RAW_DATA.DAILY_TRADES',
    REF_ENTITY_DOMAIN => 'TABLE'
  )
);

-- ============================================
-- 6. DMF計測結果の確認（スケジュール実行後）
-- ============================================

-- ※ DMFを紐付けた直後はまだ結果がありません。
-- スケジュールが実行されるまで数分お待ちください。

-- CUSTOMERS テーブルの計測結果
SELECT
  MEASUREMENT_TIME,
  TABLE_NAME,
  METRIC_NAME,
  VALUE
FROM TABLE(SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS(
  REF_ENTITY_NAME => 'SECURITIES_WORKSHOP.RAW_DATA.CUSTOMERS',
  REF_ENTITY_DOMAIN => 'TABLE'
))
ORDER BY MEASUREMENT_TIME DESC;

-- 全テーブルの最新計測結果を横断的に確認
SELECT
  MEASUREMENT_TIME,
  TABLE_NAME,
  METRIC_NAME,
  VALUE
FROM TABLE(SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS(
  REF_ENTITY_NAME => 'SECURITIES_WORKSHOP.RAW_DATA.HOLDINGS',
  REF_ENTITY_DOMAIN => 'TABLE'
))
UNION ALL
SELECT
  MEASUREMENT_TIME,
  TABLE_NAME,
  METRIC_NAME,
  VALUE
FROM TABLE(SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS(
  REF_ENTITY_NAME => 'SECURITIES_WORKSHOP.RAW_DATA.MARKET_PRICES',
  REF_ENTITY_DOMAIN => 'TABLE'
))
UNION ALL
SELECT
  MEASUREMENT_TIME,
  TABLE_NAME,
  METRIC_NAME,
  VALUE
FROM TABLE(SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS(
  REF_ENTITY_NAME => 'SECURITIES_WORKSHOP.RAW_DATA.DAILY_TRADES',
  REF_ENTITY_DOMAIN => 'TABLE'
))
ORDER BY TABLE_NAME, METRIC_NAME, MEASUREMENT_TIME DESC;

-- ============================================
-- 7. カスタムDMF: 参照整合性チェック
-- ============================================

-- システムDMFにはない「参照整合性」チェックはカスタムDMFで実現
CREATE OR REPLACE DATA METRIC FUNCTION
  SECURITIES_WORKSHOP.RAW_DATA.DMF_FK_CUSTOMER_EXISTS(
    ARG_T TABLE(CUSTOMER_ID VARCHAR)
  )
  RETURNS NUMBER
  AS
  $$
    SELECT COUNT(*)
    FROM ARG_T
    WHERE CUSTOMER_ID NOT IN (
      SELECT CUSTOMER_ID FROM SECURITIES_WORKSHOP.RAW_DATA.CUSTOMERS
    )
  $$;

-- HOLDINGS テーブルに紐付け
ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.HOLDINGS
  ADD DATA METRIC FUNCTION
    SECURITIES_WORKSHOP.RAW_DATA.DMF_FK_CUSTOMER_EXISTS ON (CUSTOMER_ID);

-- DAILY_TRADES テーブルにも紐付け
ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.DAILY_TRADES
  ADD DATA METRIC FUNCTION
    SECURITIES_WORKSHOP.RAW_DATA.DMF_FK_CUSTOMER_EXISTS ON (CUSTOMER_ID);

-- アドホック実行で動作確認
SELECT SECURITIES_WORKSHOP.RAW_DATA.DMF_FK_CUSTOMER_EXISTS(
  SELECT CUSTOMER_ID FROM SECURITIES_WORKSHOP.RAW_DATA.HOLDINGS
);

SELECT SECURITIES_WORKSHOP.RAW_DATA.DMF_FK_CUSTOMER_EXISTS(
  SELECT CUSTOMER_ID FROM SECURITIES_WORKSHOP.RAW_DATA.DAILY_TRADES
);

-- ============================================
-- 8. DMFの解除とクリーンアップ（参考）
-- ============================================

-- 個別のDMFを解除する場合:
-- ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.CUSTOMERS
--   DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);

-- スケジュールを停止する場合:
-- ALTER TABLE SECURITIES_WORKSHOP.RAW_DATA.CUSTOMERS
--   UNSET DATA_METRIC_SCHEDULE;

-- ============================================
-- 9. 手動チェック vs DMF 比較まとめ
-- ============================================
--
-- | 観点           | 手動SQL (section1)        | DMF (本セクション)              |
-- |----------------|--------------------------|--------------------------------|
-- | 実行方法       | 都度SQLを実行             | スケジュールで自動実行           |
-- | 結果の保存     | 自前のログテーブル         | Snowflakeが自動管理             |
-- | トレンド分析   | 自前で実装が必要           | DATA_QUALITY_MONITORING_RESULTS |
-- | カスタムロジック| SQLで自由に記述           | カスタムDMFとして定義            |
-- | 適用範囲       | アドホック・開発中         | 本番運用・継続監視              |
